@default_cluster_id = 10015441404448535870
@default_node_group_id = 1946097479455870976

@additional_node_group_id = 1946112512869007360


### Get default cluster info
GET {{BASE_URL}}/clusters/{{default_cluster_id}}
Authorization: Digest {{PUBLIC_KEY}} {{PRIVATE_KEY}}
Accept: application/json


### Get private link service from a node group
GET {{BASE_URL}}/clusters/{{default_cluster_id}}/tidbNodeGroups/{{default_node_group_id}}/privateLinkService
Authorization: Digest {{PUBLIC_KEY}} {{PRIVATE_KEY}}
Accept: application/json


### Get private endpoint connection from a node group
GET {{BASE_URL}}/clusters/{{default_cluster_id}}/tidbNodeGroups/{{additional_node_group_id}}/privateEndpointConnections
Authorization: Digest {{PUBLIC_KEY}} {{PRIVATE_KEY}}
Accept: application/json
